[package]
name = "moxin-mae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = "0.3.6-rc0"
eyre = "0.6.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"