[workspace]

[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = {version = "0.29.0", default-features = false, features = ["windows"] }
moly-kit = { path = "../..", features = ["full"] }
